services:
  lifeglance:
    image: ghcr.io/krelltunez/lifeglance:latest
    ports:
      - "6868:80"
    restart: unless-stopped
    depends_on:
      - proxy

  proxy:
    image: ghcr.io/krelltunez/lifeglance-proxy:latest
    restart: unless-stopped
